### ISSUE TITLE
Extend reinforth a little bit?

### ISSUE THREAD

**Issue by wboeke** [mistivia/reinforth#1]
The greater part of all interesting forth words have been implemented in reinforth, and others can be added by the user. But 2 words that would be useful are too difficult for me: ['] and :noname. Is there any chance that you could add them?

**Comment by mistivia** [comment]
This project is just a toy and now it's in archived state. I have no motivation in adding new features because there is no practical use.

For a fully functional (and embeddable) Forth, maybe you should consider [pForth](https://github.com/philburk/pforth/). It's nearly ANS compatible and also super easy to [add custom words in C](https://github.com/philburk/pforth/blob/master/csrc/pfcustom.c).

**Comment by wboeke** [comment]
In my opinion, a forth implemented in C never has practical use, because if you have a C compiler available, why would you use forth? The answer: for fun, because it is such a challenge to write something interesting in this difficult concatinateve language.
I investigated a lot of forth implementations, and reinforth is one of my favourites. It's a pity that you lost interest!
